require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MusingsController do

  # This should return the minimal set of attributes required to create a valid
  # Musing. As you add validations to Musing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MusingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all musings as @musings" do
      musing = Musing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:musings).should eq([musing])
    end
  end

  describe "GET show" do
    it "assigns the requested musing as @musing" do
      musing = Musing.create! valid_attributes
      get :show, {:id => musing.to_param}, valid_session
      assigns(:musing).should eq(musing)
    end
  end

  describe "GET new" do
    it "assigns a new musing as @musing" do
      get :new, {}, valid_session
      assigns(:musing).should be_a_new(Musing)
    end
  end

  describe "GET edit" do
    it "assigns the requested musing as @musing" do
      musing = Musing.create! valid_attributes
      get :edit, {:id => musing.to_param}, valid_session
      assigns(:musing).should eq(musing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Musing" do
        expect {
          post :create, {:musing => valid_attributes}, valid_session
        }.to change(Musing, :count).by(1)
      end

      it "assigns a newly created musing as @musing" do
        post :create, {:musing => valid_attributes}, valid_session
        assigns(:musing).should be_a(Musing)
        assigns(:musing).should be_persisted
      end

      it "redirects to the created musing" do
        post :create, {:musing => valid_attributes}, valid_session
        response.should redirect_to(Musing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved musing as @musing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musing.any_instance.stub(:save).and_return(false)
        post :create, {:musing => { "title" => "invalid value" }}, valid_session
        assigns(:musing).should be_a_new(Musing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musing.any_instance.stub(:save).and_return(false)
        post :create, {:musing => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested musing" do
        musing = Musing.create! valid_attributes
        # Assuming there are no other musings in the database, this
        # specifies that the Musing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Musing.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => musing.to_param, :musing => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested musing as @musing" do
        musing = Musing.create! valid_attributes
        put :update, {:id => musing.to_param, :musing => valid_attributes}, valid_session
        assigns(:musing).should eq(musing)
      end

      it "redirects to the musing" do
        musing = Musing.create! valid_attributes
        put :update, {:id => musing.to_param, :musing => valid_attributes}, valid_session
        response.should redirect_to(musing)
      end
    end

    describe "with invalid params" do
      it "assigns the musing as @musing" do
        musing = Musing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musing.any_instance.stub(:save).and_return(false)
        put :update, {:id => musing.to_param, :musing => { "title" => "invalid value" }}, valid_session
        assigns(:musing).should eq(musing)
      end

      it "re-renders the 'edit' template" do
        musing = Musing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musing.any_instance.stub(:save).and_return(false)
        put :update, {:id => musing.to_param, :musing => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested musing" do
      musing = Musing.create! valid_attributes
      expect {
        delete :destroy, {:id => musing.to_param}, valid_session
      }.to change(Musing, :count).by(-1)
    end

    it "redirects to the musings list" do
      musing = Musing.create! valid_attributes
      delete :destroy, {:id => musing.to_param}, valid_session
      response.should redirect_to(musings_url)
    end
  end

end
